# Generated by Django 5.0.7 on 2024-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('time_register', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('data_born', models.DateTimeField()),
                ('content', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
